version: '1.0'

services:
  db:
    build: src/main/resources/db
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  db-data:
    name: "linkedrh-training-data"
