---
version: '1'

services:
  
  db:
    build: .
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=linkedrh_training
    ports:
      - 3000:5432
