---
version: '1'

services:

  app:
    build: .
    ports:
      - 8080:8080
  
  db:
    build: src/main/resources/migrations
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
