package com.linkedrh.training.database;

import com.linkedrh.training.database.config.AppDatabaseConfig;

import org.springframework.stereotype.Component;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

@Component
public class AppDatabaseManager {

    private static Connection conn;
    private static int openedConnections = 0;

    private AppDatabase customConnection = new AppDatabase();

    public Connection openConnection() throws SQLException {
        if (AppDatabaseManager.openedConnections <= 0) {
            AppDatabaseManager.conn = DriverManager.getConnection(AppDatabaseConfig.url);
        }
        return this.customConnection;
    }

    private class AppDatabase implements Connection {

        @Override
        public void close() throws SQLException {
            AppDatabaseManager.openedConnections--;
            if (AppDatabaseManager.openedConnections <= 0) {
                AppDatabaseManager.conn.close();
            }
        }

        @Override
        public void commit() throws SQLException {
            AppDatabaseManager.conn.commit();
        }

        @Override
        public Statement createStatement() throws SQLException {
            return AppDatabaseManager.conn.createStatement();
        }

        @Override
        public Statement createStatement(int resultSetType, int resultSetConcurrency)
                throws SQLException {
            return AppDatabaseManager.conn.createStatement(resultSetType, resultSetConcurrency);
        }

        @Override
        public Statement createStatement(
                int resultSetType, int resultSetConcurrency, int resultSetHoldability)
                throws SQLException {
            return AppDatabaseManager.conn.createStatement(
                    resultSetType, resultSetConcurrency, resultSetHoldability);
        }

        @Override
        public CallableStatement prepareCall(String sql) throws SQLException {
            return AppDatabaseManager.conn.prepareCall(sql);
        }

        @Override
        public CallableStatement prepareCall(
                String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
            return AppDatabaseManager.conn.prepareCall(sql, resultSetType, resultSetConcurrency);
        }

        @Override
        public CallableStatement prepareCall(
                String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
                throws SQLException {
            return AppDatabaseManager.conn.prepareCall(
                    sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        }

        @Override
        public PreparedStatement prepareStatement(String sql) throws SQLException {
            return AppDatabaseManager.conn.prepareStatement(sql);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
                throws SQLException {
            return AppDatabaseManager.conn.prepareStatement(sql, autoGeneratedKeys);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
                throws SQLException {
            return AppDatabaseManager.conn.prepareStatement(sql, columnIndexes);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, String[] columnNames)
                throws SQLException {
            return AppDatabaseManager.conn.prepareStatement(sql, columnNames);
        }

        @Override
        public PreparedStatement prepareStatement(
                String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
            return AppDatabaseManager.conn.prepareStatement(
                    sql, resultSetType, resultSetConcurrency);
        }

        @Override
        public PreparedStatement prepareStatement(
                String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
                throws SQLException {
            return AppDatabaseManager.conn.prepareStatement(
                    sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        }

        @Override
        public void rollback() throws SQLException {
            AppDatabaseManager.conn.rollback();
        }

        @Override
        public void rollback(Savepoint savepoint) throws SQLException {
            AppDatabaseManager.conn.rollback(savepoint);
        }

        @Override
        public boolean isWrapperFor(Class<?> arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'isWrapperFor'");
        }

        @Override
        public <T> T unwrap(Class<T> arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'unwrap'");
        }

        @Override
        public void abort(Executor arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'abort'");
        }

        @Override
        public void clearWarnings() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'clearWarnings'");
        }

        @Override
        public Array createArrayOf(String arg0, Object[] arg1) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'createArrayOf'");
        }

        @Override
        public Blob createBlob() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'createBlob'");
        }

        @Override
        public Clob createClob() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'createClob'");
        }

        @Override
        public NClob createNClob() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'createNClob'");
        }

        @Override
        public SQLXML createSQLXML() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'createSQLXML'");
        }

        @Override
        public Struct createStruct(String arg0, Object[] arg1) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'createStruct'");
        }

        @Override
        public boolean getAutoCommit() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getAutoCommit'");
        }

        @Override
        public String getCatalog() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getCatalog'");
        }

        @Override
        public Properties getClientInfo() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getClientInfo'");
        }

        @Override
        public String getClientInfo(String arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getClientInfo'");
        }

        @Override
        public int getHoldability() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getHoldability'");
        }

        @Override
        public DatabaseMetaData getMetaData() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getMetaData'");
        }

        @Override
        public int getNetworkTimeout() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getNetworkTimeout'");
        }

        @Override
        public String getSchema() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getSchema'");
        }

        @Override
        public int getTransactionIsolation() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException(
                    "Unimplemented method 'getTransactionIsolation'");
        }

        @Override
        public Map<String, Class<?>> getTypeMap() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getTypeMap'");
        }

        @Override
        public SQLWarning getWarnings() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'getWarnings'");
        }

        @Override
        public boolean isClosed() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'isClosed'");
        }

        @Override
        public boolean isReadOnly() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'isReadOnly'");
        }

        @Override
        public boolean isValid(int arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'isValid'");
        }

        @Override
        public String nativeSQL(String arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'nativeSQL'");
        }

        @Override
        public void releaseSavepoint(Savepoint arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'releaseSavepoint'");
        }

        @Override
        public void setAutoCommit(boolean arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setAutoCommit'");
        }

        @Override
        public void setCatalog(String arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setCatalog'");
        }

        @Override
        public void setClientInfo(Properties arg0) throws SQLClientInfoException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setClientInfo'");
        }

        @Override
        public void setClientInfo(String arg0, String arg1) throws SQLClientInfoException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setClientInfo'");
        }

        @Override
        public void setHoldability(int arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setHoldability'");
        }

        @Override
        public void setNetworkTimeout(Executor arg0, int arg1) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setNetworkTimeout'");
        }

        @Override
        public void setReadOnly(boolean arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setReadOnly'");
        }

        @Override
        public Savepoint setSavepoint() throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setSavepoint'");
        }

        @Override
        public Savepoint setSavepoint(String arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setSavepoint'");
        }

        @Override
        public void setSchema(String arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setSchema'");
        }

        @Override
        public void setTransactionIsolation(int arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException(
                    "Unimplemented method 'setTransactionIsolation'");
        }

        @Override
        public void setTypeMap(Map<String, Class<?>> arg0) throws SQLException {
            // TODO Auto-generated method stub
            throw new UnsupportedOperationException("Unimplemented method 'setTypeMap'");
        }
    }
}
